### ISSUE TITLE
centos 6.6 rrdcached rpm not available

### ISSUE THREAD

**Issue by hprotzek** [vkhatri/chef-rrdtool#1]
Hi, unfortunately the cookbook don't work on cents 6.6, because rrdcached is not found. I couldn't find the rrdcached rpm in any repos. Is the a workaround? Cheers Holger

**Comment by vkhatri** [comment]
@hprotzek hi there! unfortunately i do not use centos os, i tested this cookbook on amazon linux. if repository do not contain the package there is little we can do.

perhaps installing from the source could be an option. i will try it out this weekend.

**Comment by hprotzek** [comment]
@vkhatri hi, any update on that? Would it be an option to work without rrdcached and only with rrdtool?

**Comment by vkhatri** [comment]
@hprotzek you are right, rrdcached is not used in every scenariao.

perhaps making rrdcached configuration optional will suffice.

**Comment by vkhatri** [comment]
@hprotzek rrdcached setup is optional now, you can disable it now.
