### ISSUE TITLE
Missing init template for debian

### ISSUE THREAD

**Issue by jamiebuxxx** [vkhatri/chef-rrdtool#2]
Hi, while trying to provisioning an Icinga2 server from the supermarket, I recieved the following error about a missing template. After taking a closer look, there does not seem to be a template for Debian based servers. 

https://github.com/vkhatri/chef-rrdtool/tree/master/templates/default
https://github.com/vkhatri/chef-rrdtool/blob/master/recipes/config.rb#L46-L53

This is an issue for Debian based servers since that template block is expecting something OS specific.

**Comment by vkhatri** [comment]
@jamiebuxxx yeah, you are right. i have not completed the setup for debian platform_family.

perhaps i can spare some time this weekend.

**Comment by vkhatri** [comment]
@jamiebuxxx have not gotten time to work on this, will work on it this week.
